In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/amazon.csv")

In [3]:
remove_columns = [
    'about_product',
    'user_id',
    'user_name',
    'review_id',
    'review_title',
    'review_content'
]
df.drop(columns=remove_columns, inplace=True, errors='ignore')

In [4]:
df['actual_price'] = (
    df['actual_price']
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [5]:
df['discounted_price'] = (
    df['discounted_price']
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [6]:
df['discount_percentage'] = (
    df['discount_percentage']
    .str.replace('%', '', regex=False)
    .astype(float)
)

In [7]:
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

In [8]:
df['rating_count'] = (
    df['rating_count']
    .astype(str)
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [9]:
df['brand'] = df['product_name'].str.split().str[0]

In [10]:
df['product_type'] = df['category'].str.split('|').str[-1]

In [11]:
df['price_difference'] = df['actual_price'] - df['discounted_price']

In [12]:
df['rating_category'] = np.where(
    df['rating'] >= 4, 'High Rated', 'Average/Low'
)

In [13]:
df['discount_flag'] = np.where(
    df['discount_percentage'] >= 50, 'High Discount', 'Low Discount'
)

In [14]:
df['availability'] = np.where(
    df.index % 4 == 0, 'Out of Stock', 'In Stock'
)

In [15]:
df['sales_category'] = np.select(
    [
        df.index % 3 == 0,
        df.index % 3 == 1
    ],
    [
        'High',
        'Medium'
    ],
    default='Low'
)

In [16]:
df['rating'].fillna(df['rating'].mean(), inplace=True)
df['rating_count'].fillna(df['rating_count'].median(), inplace=True)

/tmp/ipython-input-3542288394.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['rating'].fillna(df['rating'].mean(), inplace=True)
/tmp/ipython-input-3542288394.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['rating_count'].fillna(df['rating_count'].median(), inplace=True)

In [17]:
final_columns = [
    'product_id',
    'product_name',
    'category',
    'brand',
    'product_type',
    'actual_price',
    'discounted_price',
    'discount_percentage',
    'price_difference',
    'rating',
    'rating_count',
    'rating_category',
    'discount_flag',
    'availability',
    'sales_category',
    'img_link',
    'product_link'
]

df = df[final_columns]

In [18]:
df.head(10)

,product_id,product_name,category,brand,product_type,actual_price,discounted_price,discount_percentage,price_difference,rating,rating_count,rating_category,discount_flag,availability,sales_category,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,Wayona,USBCables,1099.0,399.00,64.0,700.00,4.2,24269.0,High Rated,High Discount,Out of Stock,High,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,Ambrane,USBCables,349.0,199.00,43.0,150.00,4.0,43994.0,High Rated,Low Discount,In Stock,Medium,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,Sounce,USBCables,1899.0,199.00,90.0,1700.00,3.9,7928.0,Average/Low,High Discount,In Stock,Low,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,boAt,USBCables,699.0,329.00,53.0,370.00,4.2,94363.0,High Rated,High Discount,In Stock,High,https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,Portronics,USBCables,399.0,154.00,61.0,245.00,4.2,16905.0,High Rated,High Discount,Out of Stock,Medium,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
5,B08Y1TFSP6,pTron Solero TB301 3A Type-C Data and Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,pTron,USBCables,1000.0,149.00,85.0,851.00,3.9,24871.0,Average/Low,High Discount,In Stock,Low,https://m.media-amazon.com/images/I/31wOPjcSxl...,https://www.amazon.in/Solero-TB301-Charging-48...
6,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro US...",Computers&Accessories|Accessories&Peripherals|...,boAt,USBCables,499.0,176.63,65.0,322.37,4.1,15188.0,High Rated,High Discount,In Stock,High,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/boAt-Micro-USB-Tangle-Fr...
7,B08DDRGWTJ,MI Usb Type-C Cable Smartphone (Black),Computers&Accessories|Accessories&Peripherals|...,MI,USBCables,299.0,229.00,23.0,70.00,4.3,30411.0,High Rated,Low Discount,In Stock,Medium,https://m.media-amazon.com/images/I/31XO-wfGGG...,https://www.amazon.in/MI-MTCY001IN-USB-Type-C-...
8,B008IFXQFU,"TP-Link USB WiFi Adapter for PC(TL-WN725N), N1...",Computers&Accessories|NetworkingDevices|Networ...,TP-Link,WirelessUSBAdapters,999.0,499.00,50.0,500.00,4.2,179691.0,High Rated,High Discount,Out of Stock,Low,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/TP-Link-TL-WN725N-150Mbp...
9,B082LZGK39,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,Ambrane,USBCables,299.0,199.00,33.0,100.00,4.0,43994.0,High Rated,Low Discount,In Stock,High,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...

In [19]:
df['price_difference'] = df['price_difference'].round(2)

In [20]:
df.isnull().sum()

product_id             0
product_name           0
category               0
brand                  0
product_type           0
actual_price           0
discounted_price       0
discount_percentage    0
price_difference       0
rating                 0
rating_count           0
rating_category        0
discount_flag          0
availability           0
sales_category         0
img_link               0
product_link           0
dtype: int64

In [21]:
df.to_csv("amazon_dashboard_ready.csv", index=False)